pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron15m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron15m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron15m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron15m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron7m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron7m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron7m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron7m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron20m20m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron20m20m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron20m20m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron20m20m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking15m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking15m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking15m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking15m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking7m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking7m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking7m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking7m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron15m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron15m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron15m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron15m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron7m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron7m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron7m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron7m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron20m20m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron20m20m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron20m20m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron20m20m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking15m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking15m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking15m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking15m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking7m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking7m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking7m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking7m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsLowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap7m4StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap7m4StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsSlowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsSlowSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsFastSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMap15m1StepsFastSpeed.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron15m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron15m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron15m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron15m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron7m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron7m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron7m15m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron7m15m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron20m20m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMapmicron20m20m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron20m20m.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMapmicron20m20m.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking15m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking15m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking15m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking15m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking7m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMaptracking7m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking7m2step.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/EKFMaptracking7m2step.pdf &
pdfcrop /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf /home/ws/matlab/registrationFourier/datasetReleaseJournal/PDFS/GTMap15m4StepsLowSpeed.pdf &
