pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
pdfcrop /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf /home/ws/matlab/registrationFourier/resultsJournalFMS2D/pdffigures/blendedScansTogether.pdf &
